abstract: Generate SVK Statistics graph.
author: Kang-min Liu <gugod@gugod.org>.
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: SVK-Churn
no_index: 
  directory: 
    - inc
    - t
requires: 
  Chart::Strip: 0
  IO::All: 0
  SVK: 0.3
version: 0.04
